name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Build container
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: zakariaabdelalizakaria/studenten-app-repo:latest,zakariaabdelalizakaria/studenten-app-repo:latest2
