name: Publish Docker Image

on:
  push:
    branches: [ master ]
  release:
    types:
      - published
        
jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v3
        
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: docker.io/zakariaabdelalizakaria/studenten-app-repo
          tag-sha: true
          tag-edge: false
          tag-latest: true
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn verify
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

        
      - name: Build the Docker image and Push
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
          docker build . --file Dockerfile --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:latest
          docker push docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPOSITORY }}:latest
        
